services:
  mongo1:
    image: mongo:7
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--port", "5571"]
    network_mode: host
    healthcheck:
      test: ["CMD", "mongosh", "--port", "5571", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  mongo2:
    image: mongo:7
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--port", "5572"]
    network_mode: host
    healthcheck:
      test: ["CMD", "mongosh", "--port", "5572", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  mongo3:
    image: mongo:7
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--port", "5573"]
    network_mode: host
    healthcheck:
      test: ["CMD", "mongosh", "--port", "5573", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
