# Образец: PGDATA primary (логическая репликация).
listen_addresses = '*'
port = 5432

wal_level = logical
max_wal_senders = 10
max_replication_slots = 10
max_logical_replication_workers = 4
max_sync_workers_per_subscription = 2
