# Образец: PGDATA primary после подключения standby (sync).
listen_addresses = '*'
port = 5432

wal_level = replica
max_wal_senders = 10
max_replication_slots = 10
hot_standby = on

synchronous_standby_names = 'standby1'
synchronous_commit = remote_apply
